//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosCURP.obtenerCurp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="obtenerCurp.curpSoap")]
    public interface curpSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento apellidopa del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generar", ReplyAction="*")]
        DatosCURP.obtenerCurp.generarResponse generar(DatosCURP.obtenerCurp.generarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generar", ReplyAction="*")]
        System.Threading.Tasks.Task<DatosCURP.obtenerCurp.generarResponse> generarAsync(DatosCURP.obtenerCurp.generarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generar", Namespace="http://tempuri.org/", Order=0)]
        public DatosCURP.obtenerCurp.generarRequestBody Body;
        
        public generarRequest() {
        }
        
        public generarRequest(DatosCURP.obtenerCurp.generarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class generarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apellidopa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellidoma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ano;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sexo;
        
        public generarRequestBody() {
        }
        
        public generarRequestBody(string apellidopa, string apellidoma, string nombres, string ano, string mes, string dia, string sexo) {
            this.apellidopa = apellidopa;
            this.apellidoma = apellidoma;
            this.nombres = nombres;
            this.ano = ano;
            this.mes = mes;
            this.dia = dia;
            this.sexo = sexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatosCURP.obtenerCurp.generarResponseBody Body;
        
        public generarResponse() {
        }
        
        public generarResponse(DatosCURP.obtenerCurp.generarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class generarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string generarResult;
        
        public generarResponseBody() {
        }
        
        public generarResponseBody(string generarResult) {
            this.generarResult = generarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface curpSoapChannel : DatosCURP.obtenerCurp.curpSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class curpSoapClient : System.ServiceModel.ClientBase<DatosCURP.obtenerCurp.curpSoap>, DatosCURP.obtenerCurp.curpSoap {
        
        public curpSoapClient() {
        }
        
        public curpSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public curpSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public curpSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public curpSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DatosCURP.obtenerCurp.generarResponse DatosCURP.obtenerCurp.curpSoap.generar(DatosCURP.obtenerCurp.generarRequest request) {
            return base.Channel.generar(request);
        }
        
        public string generar(string apellidopa, string apellidoma, string nombres, string ano, string mes, string dia, string sexo) {
            DatosCURP.obtenerCurp.generarRequest inValue = new DatosCURP.obtenerCurp.generarRequest();
            inValue.Body = new DatosCURP.obtenerCurp.generarRequestBody();
            inValue.Body.apellidopa = apellidopa;
            inValue.Body.apellidoma = apellidoma;
            inValue.Body.nombres = nombres;
            inValue.Body.ano = ano;
            inValue.Body.mes = mes;
            inValue.Body.dia = dia;
            inValue.Body.sexo = sexo;
            DatosCURP.obtenerCurp.generarResponse retVal = ((DatosCURP.obtenerCurp.curpSoap)(this)).generar(inValue);
            return retVal.Body.generarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DatosCURP.obtenerCurp.generarResponse> DatosCURP.obtenerCurp.curpSoap.generarAsync(DatosCURP.obtenerCurp.generarRequest request) {
            return base.Channel.generarAsync(request);
        }
        
        public System.Threading.Tasks.Task<DatosCURP.obtenerCurp.generarResponse> generarAsync(string apellidopa, string apellidoma, string nombres, string ano, string mes, string dia, string sexo) {
            DatosCURP.obtenerCurp.generarRequest inValue = new DatosCURP.obtenerCurp.generarRequest();
            inValue.Body = new DatosCURP.obtenerCurp.generarRequestBody();
            inValue.Body.apellidopa = apellidopa;
            inValue.Body.apellidoma = apellidoma;
            inValue.Body.nombres = nombres;
            inValue.Body.ano = ano;
            inValue.Body.mes = mes;
            inValue.Body.dia = dia;
            inValue.Body.sexo = sexo;
            return ((DatosCURP.obtenerCurp.curpSoap)(this)).generarAsync(inValue);
        }
    }
}
